global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['exchange-api-1:3001','exchange-api-2:3001','exchange-api-3:3001' ]
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_exporter:9308']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']


