openapi: 3.0.0
info:
  title: Game Exchange API
  description: API for managing games and users in an exchange list
  version: 1.0.0

  components:
  schemas:
    Game:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier for the game
        name:
          type: string
          description: The name of the game
        genre:
          type: string
          description: The genre of the game
        platform:
          type: string
          description: The gaming platform of the game

paths:
  /games:
    post:
      summary: Add a new game to the exchange list
      requestBody:
        description: Game object to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        '201':
          description: Successfully added a new game
        '400':
          description: Bad request

  /games/{gameId}:
    put:
      summary: Update all properties of a game
      parameters:
        - name: gameId
          in: path
          required: true
          description: ID of the game to be updated
          schema:
            type: string
      requestBody:
        description: Update game object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        '200':
          description: Game updated
        '404':
          description: Game not found

    patch:
      summary: Update certain properties of a game
      parameters:
        - name: gameId
          in: path
          required: true
          description: ID of the game to be updated
          schema:
            type: string
      requestBody:
        description: Partially updated game object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PartialGame'
      responses:
        '200':
          description: Game Updated
        '404':
          description: Game not found

    delete:
      summary: Remove a game from from exchange
      parameters:
        - name: gameId
          in: path
          required: true
          description: delete ID of game
          schema:
            type: string
      responses:
        '204':
          description: Game removed
        '404':
          description: Game not found

    PartialGame:
      type: object
      properties:
        name:
          type: string
          description: Name updated
        genre:
          type: int
          description: Release Year updated
        platform:
          type: int
          description: Rating updated